apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ej06ija1t-go-gitops
  description: This is GitOps manifest for ej06ija1t-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ej06ija1t-go
    janus-idp.io/tekton: ej06ija1t-go
    backstage.io/kubernetes-id: ej06ija1t-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ej06ija1t-go
