apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ej06ija1t-go
  janus-idp.io/tekton: ej06ija1t-go
  backstage.io/kubernetes-id: ej06ija1t-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ej06ija1t-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
